// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqvLRUxEn4f5HqjTZm2TwmwJiuDHHINtU',
    appId: '1:366712251908:web:55888a082fb3f590f83751',
    messagingSenderId: '366712251908',
    projectId: 'aepschoolsystem-59874',
    authDomain: 'aepschoolsystem-59874.firebaseapp.com',
    storageBucket: 'aepschoolsystem-59874.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0oW0ZNcBwBLv3FwL-H1IcyC-w0rXzNjE',
    appId: '1:366712251908:android:093ed2d4d3ca26a8f83751',
    messagingSenderId: '366712251908',
    projectId: 'aepschoolsystem-59874',
    storageBucket: 'aepschoolsystem-59874.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB94EfP0_MwEV46HcBKBAo6p-GSS54y_K0',
    appId: '1:366712251908:ios:417bf987ee7350a2f83751',
    messagingSenderId: '366712251908',
    projectId: 'aepschoolsystem-59874',
    storageBucket: 'aepschoolsystem-59874.firebasestorage.app',
    iosBundleId: 'com.example.myTestApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB94EfP0_MwEV46HcBKBAo6p-GSS54y_K0',
    appId: '1:366712251908:ios:417bf987ee7350a2f83751',
    messagingSenderId: '366712251908',
    projectId: 'aepschoolsystem-59874',
    storageBucket: 'aepschoolsystem-59874.firebasestorage.app',
    iosBundleId: 'com.example.myTestApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqvLRUxEn4f5HqjTZm2TwmwJiuDHHINtU',
    appId: '1:366712251908:web:a7ef2ba026047bb3f83751',
    messagingSenderId: '366712251908',
    projectId: 'aepschoolsystem-59874',
    authDomain: 'aepschoolsystem-59874.firebaseapp.com',
    storageBucket: 'aepschoolsystem-59874.firebasestorage.app',
  );
}
